#include "game.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
#include "logic.h"

/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"
#include "images/title.h"
#include "images/losing.h"
#include "images/winning.h"

/* TODO: */
// Add any additional states you need for your app.
typedef enum {
  START,
  START_NO_DRAW,
  PLAY_WAIT,
  PLAY,
  WIN,
  LOSE,
} GBAState;

int main(void) {

  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial game state
  GBAState state = START;

  // Loads value for secret paddles in the game, 0 is default
  int secret = 0;

  while (1) {

    currentButtons = BUTTONS;  // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {

      state = START;

    }

    switch (state) {
      
      case START:
        
        waitForVBlank();
        drawFullScreenImageDMA(TitleScreen);
        waitForVBlank();
        drawString(140, 80, "Press start", RED);

        state = START_NO_DRAW;

        break;
      
      case START_NO_DRAW:

        if (KEY_DOWN(BUTTON_START, currentButtons) && !KEY_DOWN(BUTTON_START, previousButtons)) {
          
          initGame(secret);
          state = PLAY_WAIT;
          waitForVBlank();
          fillScreenDMA(BLACK);

        } else if (KEY_DOWN(BUTTON_A, currentButtons)) {
          
          secret = 1;

        } else if (KEY_DOWN(BUTTON_B, currentButtons)) {

          secret = 2;

        } else if (KEY_DOWN(BUTTON_UP, currentButtons)) {

          secret = 3;

        } else if (KEY_DOWN(BUTTON_DOWN, currentButtons)) {

          secret = 4;

        } else if (KEY_DOWN(BUTTON_L, currentButtons) && KEY_DOWN(BUTTON_R, currentButtons)) {

          secret = 5;

        }

        break;

      case PLAY_WAIT:

        

        waitForVBlank();
        drawGameScreen();

        if ((KEY_DOWN(BUTTON_UP, currentButtons) && !KEY_DOWN(BUTTON_UP, previousButtons)) || 
            (KEY_DOWN(BUTTON_DOWN, currentButtons) && !KEY_DOWN(BUTTON_DOWN, previousButtons))) {

          state = PLAY;

        }

        break;

      case PLAY:

        waitForVBlank();
        undrawGameScreen();
        int result = processGame(currentButtons);
        if (result == 1) {

          state = WIN;
          waitForVBlank();
          fillScreenDMA(BLACK);

        } else if (result == -1) {

          state = LOSE;
          waitForVBlank();
          fillScreenDMA(BLACK);

        } else {

          drawGameScreen();

        }

        break;

      case WIN:

        waitForVBlank();
        drawFullScreenImageDMA(WinningScreen);

        if (KEY_DOWN(BUTTON_START, currentButtons)) {

          state = START;

        }
        break;
      case LOSE:

        waitForVBlank();
        drawFullScreenImageDMA(LosingScreen);

        if (KEY_DOWN(BUTTON_START, currentButtons)) {

          state = START;

        }
        break;
    }

    previousButtons = currentButtons;  // Store the current state of the buttons
  }

  return 0;
}
